# Generated by Django 2.2.5 on 2019-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncaltcontacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncedalt',
            name='last_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
