# Generated by Django 2.2.5 on 2019-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncaltcontacts', '0003_alliancecharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceContact',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=32)),
                ('standing', models.FloatField()),
            ],
        ),
    ]
