# Generated by Django 2.2.5 on 2019-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncaltcontacts', '0004_alliancecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancecharacter',
            name='last_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancecharacter',
            name='version_hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='syncedalt',
            name='version_hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
