# Generated by Django 2.2.5 on 2019-09-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_ownershiprecord'),
        ('syncaltcontacts', '0005_auto_20190916_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllianceCharacter',
            new_name='AllianceManager',
        ),
    ]
