# Generated by Django 2.2.5 on 2019-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncaltcontacts', '0006_auto_20190916_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedalt',
            name='last_error',
            field=models.IntegerField(choices=[(0, 'No error'), (1, 'Invalid token'), (99, 'Unknown error')], default=0),
        ),
    ]
