# Generated by Django 2.2.5 on 2019-09-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_ownershiprecord'),
        ('syncaltcontacts', '0007_syncedalt_last_error'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SyncedAlt',
            new_name='SyncedCharacter',
        ),
    ]
