# Generated by Django 3.1.1 on 2020-10-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0017_remove_fleetup_permission"),
        ("eveuniverse", "0002_load_eveunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncManager",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        help_text="organization contacts are fetched from",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="eveuniverse.eveentity",
                    ),
                ),
                ("version_hash", models.CharField(default="", max_length=32)),
                ("last_sync", models.DateTimeField(default=None, null=True)),
                (
                    "last_error",
                    models.IntegerField(
                        choices=[
                            (0, "No error"),
                            (1, "Invalid token"),
                            (2, "Expired token"),
                            (3, "Insufficient permissions"),
                            (4, "No character set for fetching alliance contacts"),
                            (5, "ESI API is currently unavailable"),
                            (99, "Unknown error"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "character_ownership",
                    models.ForeignKey(
                        default=None,
                        help_text="contacts are fetched from this owned character",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.characterownership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncedCharacter",
            fields=[
                (
                    "character_ownership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="authentication.characterownership",
                    ),
                ),
                (
                    "version_hash",
                    models.CharField(db_index=True, default="", max_length=32),
                ),
                ("last_sync", models.DateTimeField(default=None, null=True)),
                (
                    "last_error",
                    models.IntegerField(
                        choices=[
                            (0, "No error"),
                            (1, "Invalid token"),
                            (2, "Expired token"),
                            (3, "Insufficient permissions"),
                            (5, "ESI API is currently unavailable"),
                            (99, "Unknown error"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="standingssync.syncmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standing", models.FloatField()),
                (
                    "eve_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="standingssync.syncmanager",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("manager", "eve_entity"), name="functional_pk_evecontact"
            ),
        ),
    ]
