# Generated by Django 3.1.4 on 2021-01-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0012_index_additions'),
        ('standingssync', '0001_initial-new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncmanager',
            old_name='character',
            new_name='character_ownership',
        ),
        migrations.AlterField(
            model_name='syncmanager',
            name='alliance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='eveonline.eveallianceinfo'),
        ),
    ]
