# Generated by Django 2.2.5 on 2019-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standingssync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmanager',
            name='last_error',
            field=models.IntegerField(choices=[(0, 'No error'), (1, 'Invalid token'), (2, 'Insufficient permissions'), (3, 'No character set for fetching alliance contacts'), (99, 'Unknown error')], default=0),
        ),
        migrations.AlterField(
            model_name='syncedcharacter',
            name='last_error',
            field=models.IntegerField(choices=[(0, 'No error'), (1, 'Invalid token'), (2, 'Insufficient permissions'), (99, 'Unknown error')], default=0),
        ),
    ]
