# Generated by Django 3.1.4 on 2021-01-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standingssync', '0002_auto_20210109_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncedcharacter',
            old_name='character',
            new_name='character_ownership',
        ),
    ]
